# Railway Deployment Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run main.py --server.port=${PORT:-8080} --server.address=0.0.0.0 --server.headless=true"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
# Streamlit configuration
STREAMLIT_SHARING = "true"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

# Authentication settings
AUTH_SECRET_KEY = "your-secret-key-change-this-in-production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "change-this-password"

# AI and API settings
GROQ_API_KEY = "$GROQ_API_KEY"
ALPHA_VANTAGE_API_KEY = "$ALPHA_VANTAGE_API_KEY"
NEWS_API_KEY = "$NEWS_API_KEY"

# Trading configuration
VIRTUAL_MONEY_AMOUNT = "100000"
DEFAULT_COMMISSION = "0.1"
LOG_LEVEL = "INFO"
DEBUG = "false"
