# Railway Deployment Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'Starting Streamlit on port' $PORT && streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --browser.gatherUsageStats false --server.enableCORS false --server.enableXsrfProtection false"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
# Streamlit configuration
STREAMLIT_SHARING = "true"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

# Authentication settings
AUTH_SECRET_KEY = "db00a3aec8daf7ef2117ddc1475bfda8b1983784b5ef2389a10189942d379cd6"
ADMIN_USERNAME = "admin_3qwrjj3b"
ADMIN_PASSWORD = "$N9mwR#3a#Ilm^2l"

# AI and API settings
GROQ_API_KEY = "$GROQ_API_KEY"
ALPHA_VANTAGE_API_KEY = "$ALPHA_VANTAGE_API_KEY"
NEWS_API_KEY = "$NEWS_API_KEY"

# Trading configuration
VIRTUAL_MONEY_AMOUNT = "100000"
DEFAULT_COMMISSION = "0.1"
LOG_LEVEL = "INFO"
DEBUG = "false"
